---
# tasks file for proxy_settings

- name: Configure proxy settings for OS (/etc/environment)
  blockinfile:
    dest: /etc/environment
    create: yes
    block: |
      {% if proxy_settings_http_proxy is defined %}
      http_proxy="{{ proxy_settings_http_proxy }}"
      HTTP_PROXY="{{ proxy_settings_http_proxy }}"
      {% endif %}
      {% if proxy_settings_ftp_proxy is defined %}
      ftp_proxy="{{ proxy_settings_ftp_proxy }}"
      FTP_PROXY="{{ proxy_settings_ftp_proxy }}"
      {% endif %}
      {% if proxy_settings_https_proxy is defined %}
      https_proxy="{{ proxy_settings_https_proxy }}"
      HTTPS_PROXY="{{ proxy_settings_https_proxy }}"
      {% endif %}
      {% if proxy_settings_no_proxy is defined %}
      no_proxy="{{ proxy_settings_no_proxy }}"
      NO_PROXY="{{ proxy_settings_no_proxy }}"
      {% endif %}
  tags: proxy

- name: Configure proxy settings for OS (/etc/profile.d/proxy.sh)
  template: src=proxy.sh.j2 dest=/etc/profile.d/proxy.sh
  tags: proxy

- name: Check if wgetrc exists
  stat: path=/etc/wgetrc
  register: wgetrc
  tags: proxy

- name: Add proxy settings to wgetrc (if exists)
  blockinfile:
    dest: /etc/wgetrc
    block: |
      use_proxy = on
      http_proxy = {{ proxy_settings_http_proxy }}
      https_proxy = {{ proxy_settings_https_proxy }}
      ftp_proxy = {{ proxy_settings_ftp_proxy }}
      no_proxy = {{ proxy_settings_no_proxy }}
  when: wgetrc.stat.exists
  tags: proxy

- name: Configure proxy settings for yum
  block:
    - name: Configure proxy settings w/o id/pw for yum
      blockinfile:
        dest: /etc/yum.conf
        block: |
          proxy={{ proxy_settings_yum_proxy }}
      tags: proxy
      when: proxy_settings_yum_proxy_username is undefined

    - name: Configure proxy settings and id/pw for yum
      blockinfile:
        dest: /etc/yum.conf
        block: |
          proxy={{ proxy_settings_yum_proxy }}
          proxy_username={{ proxy_settings_yum_proxy_username }}
          proxy_password={{ proxy_settings_yum_proxy_password }}
      tags: proxy
      when: proxy_settings_yum_proxy_username is defined
  tags: proxy
  when: ansible_os_family == 'RedHat' and proxy_settings_yum_proxy is defined

- name: Configure proxy settings for apt-get/aptitude
  template: src=80proxy.j2 dest=/etc/apt/apt.conf.d/80proxy
  tags: proxy
  when: ansible_os_family == 'Debian'

- name: Configure proxy settings for Suse
  template: src=proxy.j2 dest=/etc/sysconfig/proxy
  tags: proxy
  when: ansible_os_family == 'Suse'
